{
 "title": "Compare System Parameters",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "OS_Compare",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_boot_time_seconds, node_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "content": "<h1><i><font color=#5991A7><b><center>System Information</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$host - System Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "repeat": "host",
   "targets": [
    {
     "expr": "node_uname_info{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - System Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "node_uname_info{node_name=~\"$host\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$host - System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
   "repeat": "host",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{node_name=~\"$host\"} - node_boot_time_seconds{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{node_name=~\"$host\"} - node_boot_time_seconds{node_name=~\"$host\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "$host - CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 13 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{node_name=~\"$host\", mode=\"system\"})"
    }
   ]
  },
  {
   "title": "$host - CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{node_name=~\"$host\", mode=\"system\"})"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$host - RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 16 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=~\"$host\"}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$host - Saturation Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(avg_over_time(node_procs_running{node_name=~\"$host\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})) or (avg_over_time(node_procs_running{node_name=~\"$host\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg_over_time(node_procs_blocked{node_name=~\"$host\"}[$interval]) or avg_over_time(node_procs_blocked{node_name=~\"$host\"}[5m])",
     "legendFormat": "IO Load "
    }
   ]
  },
  {
   "title": "$host - Saturation Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(avg_over_time(node_procs_running{node_name=~\"$host\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})) or (avg_over_time(node_procs_running{node_name=~\"$host\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg_over_time(node_procs_blocked{node_name=~\"$host\"}[$interval]) or avg_over_time(node_procs_blocked{node_name=~\"$host\"}[5m])",
     "legendFormat": "IO Load "
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$host - Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node_name=~\"$host\"} ",
     "legendFormat": "LoadAvg 1m"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})",
     "legendFormat": "VCPUs"
    }
   ]
  },
  {
   "title": "$host - Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{node_name=~\"$host\"} ",
     "legendFormat": "LoadAvg 1m"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"})",
     "legendFormat": "VCPUs"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "content": "<h1><i><font color=#5991A7><b><center>CPU</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "$host - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$host - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "$host - Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_intr_total{node_name=~\"$host\"}[$interval]) or irate(node_intr_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    },
    {
     "expr": "(rate(node_intr_total{node_name=~\"$host\"}[$interval]) or irate(node_intr_total{node_name=~\"$host\"}[5m])) /scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
     "legendFormat": "Interrupts per VCPU"
    }
   ]
  },
  {
   "title": "$host - Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_intr_total{node_name=~\"$host\"}[$interval]) or irate(node_intr_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    },
    {
     "expr": "(rate(node_intr_total{node_name=~\"$host\"}[$interval]) or irate(node_intr_total{node_name=~\"$host\"}[5m])) /scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
     "legendFormat": "Interrupts per VCPU"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "$host - Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{node_name=~\"$host\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "(rate(node_context_switches_total{node_name=~\"$host\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$host\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
     "legendFormat": "Context Switches per Virtual CPU"
    }
   ]
  },
  {
   "title": "$host - Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_context_switches_total{node_name=~\"$host\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "(rate(node_context_switches_total{node_name=~\"$host\"}[$interval]) or irate(node_context_switches_total{node_name=~\"$host\"}[5m])) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$host\"}))",
     "legendFormat": "Context Switches per Virtual CPU"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 62 },
   "content": "<h1><i><font color=#5991A7><b><center>Memory</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "$host - Memory  Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{node_name=~\"$host\"}) without(job) - (max(node_memory_MemFree_bytes{node_name=~\"$host\"}) without(job) + max(node_memory_Buffers_bytes{node_name=~\"$host\"}) without(job) + (max(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-enhanced|rds-basic|node.*\"}) without (job)))",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{node_name=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{node_name=~\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-enhanced|rds-basic|node.*\"}) without (job)",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "$host - Memory  Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{node_name=~\"$host\"}) without(job) - \n(max(node_memory_MemFree_bytes{node_name=~\"$host\"}) without(job) + \nmax(node_memory_Buffers_bytes{node_name=~\"$host\"}) without(job) + \n(max(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached_bytes{node_name=~\"$host\",job=\"rds-basic\"}) without (job)))",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{node_name=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{node_name=~\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-enhanced|linux\"}) without (job) or \nmax(node_memory_Cached_bytes{node_name=~\"$host\",job=~\"rds-basic\"}) without (job)",
     "legendFormat": "Cached"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "$host - Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal_bytes{node_name=~\"$host\"} - node_memory_SwapFree_bytes{node_name=~\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree_bytes{node_name=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{node_name=~\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$host - Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal_bytes{node_name=~\"$host\"} - node_memory_SwapFree_bytes{node_name=~\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree_bytes{node_name=~\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{node_name=~\"$host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "$host - Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "rate(node_vmstat_pswpout{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  },
  {
   "title": "$host - Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In (Reads)"
    },
    {
     "expr": "rate(node_vmstat_pswpout{node_name=~\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=~\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out (Writes)"
    }
   ]
  },
  { "title": "Disk partitions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 89 },
   "content": "<h1><i><font color=#5991A7><b><center>Disk partitions</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "$host - Mountpoint Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} / node_filesystem_size_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "$host - Mountpoint Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} / node_filesystem_size_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "$host - Free Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 100 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "$host - Free Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{node_name=~\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} ",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Disk performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 108 },
   "content": "<h1><i><font color=#5991A7><b><center>Disk performance</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "$host - I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "$host - I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "$host - Disk Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
   "repeat": "host",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{node_name=~'$host'}[$interval]) or irate(node_disk_reads_completed_total{node_name=~'$host'}[5m])",
     "legendFormat": "Reads: {{device}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{node_name=~'$host'}[$interval]) or irate(node_disk_writes_completed_total{node_name=~'$host'}[5m])",
     "legendFormat": "Writes: {{device}}"
    }
   ]
  },
  {
   "title": "$host - Disk Operations",
   "type": "graph",
   "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{node_name=~'$host'}[$interval]) or irate(node_disk_reads_completed_total{node_name=~'$host'}[5m])",
     "legendFormat": "Reads: {{device}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{node_name=~'$host'}[$interval]) or irate(node_disk_writes_completed_total{node_name=~'$host'}[5m])",
     "legendFormat": "Writes: {{device}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "$host - Disk Bandwidth",
   "type": "graph",
   "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node_name=~\"$host\"}[$interval]) or irate(node_disk_read_bytes_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Reads: {{device}} "
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node_name=~\"$host\"}[$interval]) or irate(node_disk_written_bytes_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Writes: {{device}} "
    }
   ]
  },
  {
   "title": "$host - Disk Bandwidth",
   "type": "graph",
   "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{node_name=~\"$host\"}[$interval]) or irate(node_disk_read_bytes_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Reads: {{device}} "
    },
    {
     "expr": "rate(node_disk_written_bytes_total{node_name=~\"$host\"}[$interval]) or irate(node_disk_written_bytes_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Writes: {{device}} "
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "$host - Disk IO Utilization",
   "type": "graph",
   "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 135 },
   "repeat": "host",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node_name=~\"$host\"}[$interval]) or irate(node_disk_io_time_seconds_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "$host - Disk IO Utilization",
   "type": "graph",
   "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{node_name=~\"$host\"}[$interval]) or irate(node_disk_io_time_seconds_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "$host - Disk Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
   "repeat": "host",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) or \n(irate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[5m]) / \nirate(node_disk_reads_completed_total{node_name=~\"$host\"}[5m]))\nor avg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[5m])/1000",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) or \n(irate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[5m]) / \nirate(node_disk_writes_completed_total{node_name=~\"$host\"}[5m]))\nor (avg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[5m])/1000)",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "$host - Disk Latency",
   "type": "graph",
   "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_reads_completed_total{node_name=~\"$host\"}[$interval])) or \n(irate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[5m]) / \nirate(node_disk_reads_completed_total{node_name=~\"$host\"}[5m]))\nor avg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_read_latency_average{node_name=~\"$host\"}[5m])/1000",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "(rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) / \nrate(node_disk_writes_completed_total{node_name=~\"$host\"}[$interval])) or \n(irate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[5m]) / \nirate(node_disk_writes_completed_total{node_name=~\"$host\"}[5m]))\nor (avg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[$interval])/1000 or \navg_over_time(aws_rds_write_latency_average{node_name=~\"$host\"}[5m])/1000)",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "$host - Disk Load",
   "type": "graph",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  {
   "title": "$host - Disk Load",
   "type": "graph",
   "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_read_time_seconds_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Read: {{ device }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[$interval]) or \nirate(node_disk_write_time_seconds_total{node_name=~\"$host\"}[5m])",
     "legendFormat": "Write: {{ device }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 159 },
   "content": "<h1><i><font color=#5991A7><b><center>Network</center></b></font></i></h1>"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 162 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "Bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m])) ",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 170 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}