{
 "title": "Home Dashboard",
 "tags": [
  "Percona",
  "PMM"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(node_boot_time_seconds, environment)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_boot_time_seconds{environment=~\"$environment\"}, node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values({__name__=~\"postgres_exporter_build_info|mysqld_exporter_build_info|mongodb_exporter_build_info|proxysql_exporter_build_info\",node_name=~\"$host\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "content": "<br>\n<div class=\"text-center dashboard-header\">\n<img src=\"/graph/public/plugins/pmm-app/img/pmm-logo.svg\" height=\"60px\" width=\"60px\">\n  <span>Percona Monitoring and Management</span>\n</div>"
  },
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "content": "**Overview**  \n[Percona Monitoring and Management (PMM)](https://www.percona.com/pmm) is a free and open-source platform for managing and monitoring MySQL and MongoDB performance, and provides time-based analysis to ensure that your data works as efficiently as possible. \n\n**Documentation**  \nPlease consult the official [PMM documentation](https://www.percona.com/doc/percona-monitoring-and-management/index.html) to learn more about PMM. Also of interest are the [Release notes](https://www.percona.com/doc/percona-monitoring-and-management/release-notes/index.html) and [FAQ](https://www.percona.com/doc/percona-monitoring-and-management/faq.html) for common questions about PMM.\n\n**Community and Blogs**  \nOn the [PMM Community Forums](https://www.percona.com/forums/questions-discussions/percona-monitoring-and-management) you will find help from Perconians and the Community at large.  Further, we publish PMM announcements and use cases regularly on the [Percona Database Performance Blog](https://www.percona.com/blog/category/percona-monitoring-and-management/)  \n\n**Get Help from Percona**  \nAre you looking for assistance that comes with a response-time guarantee? Let our [Support team](https://www.percona.com/services/support?utm_source=pmm&utm_medium=web&utm_campaign=support_link)  help you!\nAlready a customer? Log in to your [Percona Support Portal](https://customers.percona.com) \n\n\n\n"
  },
  {
   "title": "Starred and Recently used Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 8 }
  },
  {
   "title": "Systems under monitoring",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "Monitored DB Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(mysql_global_status_uptime{node_name=~\"$host\"} or \nmongodb_up {node_name=~\"$host\"} or \npg_up{node_name=~\"$host\"} or \npostgresql_up{node_name=~\"$host\"})"
    }
   ]
  },
  {
   "type": "pmm-update-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {}
   ]
  },
  { "title": "Environment Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Host", "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 }, "content": "<b>All</b>" },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by () ((sum by (node_name,cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or  (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) ))*100 or sum by () (avg_over_time(node_cpu_average{node_name=~\"$host\",mode!=\"idle\", mode!=\"total\",mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$host\",mode!=\"idle\",mode!=\"total\",mode!=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Mem Avail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg by () ((node_memory_MemAvailable_bytes{node_name=~\"$host\"} or (node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) / node_memory_MemTotal_bytes{node_name=~\"$host\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 20 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m])) * 1024"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 20 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m])) * 1024"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 20 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(node_network_receive_bytes_total{node_name=~\"$host\",device!=\"lo\"}[$interval]) \nor irate(node_network_receive_bytes_total{node_name=~\"$host\",device!=\"lo\"}[5m]) \nor max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval]) \nor max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m]))\n+\nsum(rate(node_network_transmit_bytes_total{node_name=~\"$host\",device!=\"lo\"}[$interval]) \nor irate(node_network_transmit_bytes_total{node_name=~\"$host\",device!=\"lo\"}[5m])\nor max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval]) \nor max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "DB Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (max_over_time(mysql_global_status_threads_connected{node_name=~\"$host\"}[$interval]) or \nmax_over_time(mongodb_connections{node_name=~\"$host\",state=\"current\"}[$interval]) or\nsum by (node_name) (max_over_time(pg_stat_database_numbackends{node_name=~\"$host\"}[$interval])))"
    }
   ]
  },
  {
   "title": "DB QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 20 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (\n(rate(mysql_global_status_queries{node_name=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{node_name=~\"$host\"}[5m])) or \n(sum(rate(mongodb_mongod_op_counters_total{node_name=~\"$host\",type!=\"command\"}[$interval])) or \nsum(irate(mongodb_mongod_op_counters_total{node_name=~\"$host\",type!=\"command\"}[5m]))) or\n(sum(rate(pg_stat_database_xact_commit{node_name=~\"$host\"}[$interval]) + \nrate(pg_stat_database_xact_rollback{node_name=~\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_xact_commit{node_name=~\"$host\"}[5m]) + \nirate(pg_stat_database_xact_rollback{node_name=~\"$host\"}[5m])))\n)"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}) or \n(1-absent(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{node_name=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 20 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal_bytes{node_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Host uptime",
   "type": "singlestat",
   "description": "AVG   Uptime for  `All`",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 20 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_time_seconds{node_name=~\"$host\"} - node_boot_time_seconds{node_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "DB uptime",
   "type": "singlestat",
   "description": "AVG for  `All`",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 20 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg(mysql_global_status_uptime{node_name=~\"$host\"} or \nmongodb_instance_uptime_seconds {node_name=~\"$host\"} or \n(time() - process_start_time_seconds{node_name=~\"$host\",job=~\"postgres_exporter.*\"}))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "host" },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 }, "content": "$host" },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name) (sum by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by () (avg_over_time(node_cpu_average{node_name=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[5m]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{node_name=~\"$host\"} or (node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) / node_memory_MemTotal_bytes{node_name=~\"$host\"} * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 24 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 24 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 24 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m]))) + \n(sum(rate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m]))) "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by (node_name) (max_over_time(mysql_global_status_threads_connected{node_name=~\"$host\"}[$interval]) or \nmax_over_time(mongodb_connections{node_name=~\"$host\",state=\"current\"}[$interval]) or\nsum by (node_name) (max_over_time(pg_stat_database_numbackends{node_name=~\"$host\"}[$interval])))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 24 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by (node_name) (\n(rate(mysql_global_status_queries{node_name=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{node_name=~\"$host\"}[5m])) or \n(sum by (node_name) (rate(mongodb_mongod_op_counters_total{node_name=~\"$host\",type!=\"command\"}[$interval])) or \nsum by (node_name) (irate(mongodb_mongod_op_counters_total{node_name=~\"$host\",type!=\"command\"}[5m]))) or\n(sum by (node_name) (rate(pg_stat_database_xact_commit{node_name=~\"$host\"}[$interval]) + \nrate(pg_stat_database_xact_rollback{node_name=~\"$host\"}[$interval])) or\nsum by (node_name) (irate(pg_stat_database_xact_commit{node_name=~\"$host\"}[5m]) + \nirate(pg_stat_database_xact_rollback{node_name=~\"$host\"}[5m])))\n)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}))) + \nsum(rdsosmetrics_General_numVCPUs{node_name=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 24 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{node_name=~\"$host\"} - node_boot_time_seconds{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 24 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (node_name) (mysql_global_status_uptime{node_name=~\"$host\"} or \nmongodb_instance_uptime_seconds {node_name=~\"$host\"} or \n(time() - process_start_time_seconds{node_name=~\"$host\",job=~\"postgres_exporter.*\"}))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 28 }, "content": "$host" },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(avg by (node_name) (sum by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or(clamp_max(irate(node_cpu_seconds_total{node_name=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by () (avg_over_time(node_cpu_average{node_name=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[5m]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{node_name=~\"$host\"} or (node_memory_MemFree_bytes{node_name=~\"$host\"} + node_memory_Buffers_bytes{node_name=~\"$host\"} + node_memory_Cached_bytes{node_name=~\"$host\"})) / node_memory_MemTotal_bytes{node_name=~\"$host\"} * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 28 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgin{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 28 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgout{node_name=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 28 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{node_name=~\"$host\"}[5m]))) + \n(sum(rate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes_total{node_name=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{node_name=~\"$host\"}[5m]))) "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by (node_name) (max_over_time(mysql_global_status_threads_connected{node_name=~\"$host\"}[$interval]) or \nmax_over_time(mongodb_connections{node_name=~\"$host\",state=\"current\"}[$interval]) or\nsum by (node_name) (max_over_time(pg_stat_database_numbackends{node_name=~\"$host\"}[$interval])))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by (node_name) (\n(rate(mysql_global_status_queries{node_name=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{node_name=~\"$host\"}[5m])) or \n(sum by (node_name) (rate(mongodb_mongod_op_counters_total{node_name=~\"$host\",type!=\"command\"}[$interval])) or \nsum by (node_name) (irate(mongodb_mongod_op_counters_total{node_name=~\"$host\",type!=\"command\"}[5m]))) or\n(sum by (node_name) (rate(pg_stat_database_xact_commit{node_name=~\"$host\"}[$interval]) + \nrate(pg_stat_database_xact_rollback{node_name=~\"$host\"}[$interval])) or\nsum by (node_name) (irate(pg_stat_database_xact_commit{node_name=~\"$host\"}[5m]) + \nirate(pg_stat_database_xact_rollback{node_name=~\"$host\"}[5m])))\n)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu_seconds_total{node_name=~\"$host\",mode=~\"user\"}))) + \nsum(rdsosmetrics_General_numVCPUs{node_name=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 28 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 28 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{node_name=~\"$host\"} - node_boot_time_seconds{node_name=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 28 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by (node_name) (mysql_global_status_uptime{node_name=~\"$host\"} or \nmongodb_instance_uptime_seconds {node_name=~\"$host\"} or \n(time() - process_start_time_seconds{node_name=~\"$host\",job=~\"postgres_exporter.*\"}))"
    }
   ]
  }
 ]
}