{
 "title": "MongoDB Cluster Summary",
 "tags": [
  "MongoDB",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mongodb_up{cluster=\"$cluster\"},service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unsharded DBs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{cluster=\"$cluster\", type=\"unpartitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded DBs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{cluster=\"$cluster\", type=\"partitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Sharded Collections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_collections_total{cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_total{cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_chunks_total{cluster=\"$cluster\"})",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Balancer Enabled",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_balancer_enabled{cluster=\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Chunks Balanced",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_mongos_sharding_chunks_is_balanced{cluster=\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Mongos Operations Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongos Operations Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongos Operations $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "repeat": "service",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Mongos Operations $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Mongos Operations $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Mongos Operations $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=\"$service\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Mongos  Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (mongodb_connections{cluster=\"$cluster\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Mongos  Cursors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"} or mongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\"})",
     "legendFormat": "Cursors"
    }
   ]
  },
  {
   "title": "Mongos Connections Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongos  Connections $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (mongodb_connections{cluster=\"$cluster\",service_name=\"$service\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Mongos  Connections $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (mongodb_connections{cluster=\"$cluster\",service_name=\"$service\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Mongos  Connections $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (mongodb_connections{cluster=\"$cluster\",service_name=\"$service\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Mongos  Connections $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (mongodb_connections{cluster=\"$cluster\",service_name=\"$service\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mongos  Cursors Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongos  Cursors $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\",service_name=\"$service\"} or\nmongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\",service_name=\"$service\"})",
       "legendFormat": "Cursors"
      }
     ]
    },
    {
     "title": "Mongos  Cursors $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\",service_name=\"$service\"} or\nmongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\",service_name=\"$service\"})",
       "legendFormat": "Cursors"
      }
     ]
    },
    {
     "title": "Mongos  Cursors $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\",service_name=\"$service\"} or\nmongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\",service_name=\"$service\"})",
       "legendFormat": "Cursors"
      }
     ]
    },
    {
     "title": "Mongos  Cursors $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\",service_name=\"$service\"} or\nmongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\",service_name=\"$service\"})",
       "legendFormat": "Cursors"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Chunk Split Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\"}[$interval])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Change Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*(shard|Shard).*\"}[$interval])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Chunk Split Events Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunk Split Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Chunk Split Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Chunk Split Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Chunk Split Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Change Log Events Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Change Log Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*(shard|Shard).*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Change Log Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*(shard|Shard).*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Change Log Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*(shard|Shard).*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Change Log Events $service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*(shard|Shard).*\",service_name=\"$service\"}[$interval])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Operations Per Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[5m])) by (instance) * on (instance) \ngroup_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Chunks by Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Connections Per Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connections{cluster=\"$cluster\", state=\"current\"} * on (instance) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Cursors Per Shard",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"} or mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Replication Lag by Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(mongodb_mongod_replset_member_optime_date{cluster=\"$cluster\", state=\"PRIMARY\"}) by (set) - min(mongodb_mongod_replset_member_optime_date{cluster=\"$cluster\", state=\"SECONDARY\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Oplog Range by Set",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_replset_oplog_head_timestamp{cluster=\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{cluster=\"$cluster\"}) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Shard Elections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(changes(mongodb_mongod_replset_member_election_date{cluster=\"$cluster\"}[$interval])) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Collection Lock Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_locks_time_locked_global_microseconds_total{cluster=\"$cluster\", database=\"Collection\"}) by (instance) * on (instance) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  }
 ]
}