{
 "title": "MySQL MyISAM/Aria Metrics",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up,node_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mysql_up{node_name=~\"$host\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "MyISAM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MyISAM Indexes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_reads{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_key_reads{service_name=\"$service\"}[5m])",
     "legendFormat": "Key Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_read_requests{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_key_read_requests{service_name=\"$service\"}[5m])",
     "legendFormat": "Key Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_writes{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_key_writes{service_name=\"$service\"}[5m])",
     "legendFormat": "Key Writes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_write_requests{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_key_write_requests{service_name=\"$service\"}[5m])",
     "legendFormat": "Key Write Requests"
    }
   ]
  },
  {
   "title": "MyISAM Key Buffer Performance",
   "type": "graph",
   "description": "The `Key Read Ratio`  (Key_reads/Key_read_requests) ratio should normally be less than 0.01.\n\nThe  `Key Write Ratio` (Key_writes/Key_write_requests) ratio is usually near 1 if you are using mostly updates and deletes, but might be much smaller if you tend to do updates that affect many rows at the same time or if you are using the `DELAY_KEY_WRITE` table option.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_reads{service_name=\"$service\"}[$interval]) / rate(mysql_global_status_key_read_requests{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_key_reads{service_name=\"$service\"}[5m]) / irate(mysql_global_status_key_read_requests{service_name=\"$service\"}[5m])",
     "legendFormat": "Key Read Ratio"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_key_writes{service_name=\"$service\"}[$interval]) / rate(mysql_global_status_key_write_requests{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_key_writes{service_name=\"$service\"}[5m]) / irate(mysql_global_status_key_write_requests{service_name=\"$service\"}[5m])",
     "legendFormat": "Key Write Ratio"
    }
   ]
  },
  {
   "title": "MyISAM Key Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_key_buffer_size{service_name=\"$service\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_key_buffer_size{service_name=\"$service\"} - mysql_global_status_key_blocks_unused{service_name=\"$service\"} * mysql_global_variables_key_cache_block_size{service_name=\"$service\"}",
     "legendFormat": "Key Blocks Used"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_key_blocks_not_flushed{service_name=\"$service\"} * mysql_global_variables_key_cache_block_size{service_name=\"$service\"}",
     "legendFormat": "Key Blocks Not Flushed"
    }
   ]
  },
  { "title": "Aria Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Aria Pagecache Reads/Writes",
   "type": "graph",
   "description": "This graph is similar to InnoDB buffer pool reads/writes. `aria-pagecache-buffer-size` is the main cache for the Aria storage engine. If you see high reads/writes (physical IO), i.e. reads are close to read requests and/or writes are close to write requests you may need to increase the `aria-pagecache-buffer-size` (may need to decrease other buffers: `key_buffer_size`, `innodb_buffer_pool_size`, etc.)",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_write_requests{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_aria_pagecache_write_requests{service_name=\"$service\"}[5m])",
     "legendFormat": "Aria Pagecache Write Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_read_requests{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_aria_pagecache_read_requests{service_name=\"$service\"}[5m])",
     "legendFormat": "Aria Pagecache Read Requests"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_reads{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_aria_pagecache_reads{service_name=\"$service\"}[5m])",
     "legendFormat": "Aria Pagecache Reads"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_aria_pagecache_writes{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_aria_pagecache_writes{service_name=\"$service\"}[5m])",
     "legendFormat": "Aria Pagecache Writes"
    }
   ]
  },
  {
   "title": "Aria Storage Engine",
   "type": "text",
   "description": "The Aria storage is specific to MariaDB Server. Aria has most of the same variables that MyISAM has, but with an Aria prefix. If you use Aria instead of MyISAM, then you should make key-buffer-size smaller and aria-pagecache-buffer-size bigger.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "content": "The Aria Storage Engine ships only with MariaDB so you should expect to see empty Aria graphs if you are running Percona Server for MySQL, MySQL Community, or MySQL Enterprise."
  },
  {
   "title": "Aria Transaction Log Syncs",
   "type": "graph",
   "description": "This is similar to InnoDB log file syncs. If you see lots of log syncs and want to relax the durability settings you can change `aria_checkpoint_interval` (in seconds) from 30 (default) to a higher number. It is good to look at the disk IO dashboard as well.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_aria_transaction_log_syncs{service_name=\"$service\"}[$interval]) or irate(mysql_global_status_aria_transaction_log_syncs{service_name=\"$service\"}[5m])",
     "legendFormat": "Aria Transaction Log Syncs"
    }
   ]
  },
  {
   "title": "Aria Pagecache Blocks",
   "type": "graph",
   "description": "This graph shows the utilization for the Aria pagecache. This is similar to InnDB buffer pool graph. If you see all blocks are used you may consider increasing `aria-pagecache-buffer-size` (may need to decrease other buffers: `key_buffer_size`, `innodb_buffer_pool_size`, etc.)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aria_pagecache_blocks_not_flushed{service_name=\"$service\"}",
     "legendFormat": "Aria Pagecache Blocks Not Flushed"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aria_pagecache_blocks_used{service_name=\"$service\"}",
     "legendFormat": "Aria Pagecache Blocks Used"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aria_pagecache_blocks_unused{service_name=\"$service\"}",
     "legendFormat": "Aria Pagecache Blocks Unused"
    },
    {
     "expr": "mysql_global_variables_aria_pagecache_buffer_size{service_name=\"$service\"} / mysql_global_variables_aria_block_size{service_name=\"$service\"}",
     "legendFormat": "Aria Pagecache Total Blocks"
    }
   ]
  }
 ]
}