{
 "title": "ProxySQL Overview",
 "tags": [
  "Percona",
  "HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "proxysql",
    "label": "ProxySQL Instance",
    "query": "label_values(proxysql_mysql_status_active_transactions, node_name)"
   },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "label_values(proxysql_connection_pool_status{node_name=\"$proxysql\"}, hostgroup)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "ProxySQL Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Hostgroup Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "scalar(count(proxysql_connection_pool_status{node_name=\"$proxysql\", hostgroup=\"$hostgroup\"}))",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Client Connections (All Host Groups)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_mysql_status_client_connections_connected{node_name=\"$proxysql\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Client Questions (All Host Groups)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Question Rate"
    }
   ]
  },
  {
   "title": "Active Backend Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_connection_pool_conn_used{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Failed Backend Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_connection_pool_conn_err{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or irate(proxysql_connection_pool_conn_err{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Active Frontend Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(proxysql_processlist_client_connection_list{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_processlist_client_connection_list{node_name=\"$proxysql\"}[5m]) ",
     "legendFormat": "{{ client_host }}"
    }
   ]
  },
  {
   "title": "Client Frontend Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(proxysql_processlist_detailed_client_connection_count{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\"}[$interval]) or max_over_time(proxysql_processlist_detailed_client_connection_count{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Connection Pool Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Endpoint Status",
   "type": "table",
   "description": "Status number to state mapping:\n\n1 `ONLINE`\n\n2 `SHUNNED`\n\n3 `OFFLINE_SOFT`\n\n4 `OFFLINE_HARD`\n\nFor status details, see the [description](https://github.com/sysown/proxysql/blob/master/doc/admin_tables.md#mysql_servers).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "proxysql_connection_pool_status{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Queries Routed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_connection_pool_queries{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or irate(proxysql_connection_pool_queries{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Query processor time efficecy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(proxysql_mysql_status_query_processor_time_nsec{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_query_processor_time_nsec{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "QP_efficiency_query"
    },
    {
     "expr": "(rate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Questions"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Connection Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_connection_pool_conn_free{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_connection_pool_latency_us{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Query Cache memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}",
     "legendFormat": "QC Total Memory used"
    },
    {
     "expr": "proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}/proxysql_mysql_status_query_cache_entries{node_name=\"$proxysql\"}",
     "legendFormat": "Bytes for cached query avg"
    }
   ]
  },
  {
   "title": "Query Cache efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "((rate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[5m])))        ",
     "legendFormat": "Query Cache GET efficiency"
    },
    {
     "expr": "((rate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[5m])))        ",
     "legendFormat": "Insert VS read efficiency (high is good)"
    }
   ]
  },
  {
   "title": "Network Traffic and Mirroring efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(proxysql_connection_pool_bytes_data_recv{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) + rate(proxysql_connection_pool_bytes_data_sent{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval])) or (irate(proxysql_connection_pool_bytes_data_recv{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]) + irate(proxysql_connection_pool_bytes_data_sent{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Mirroring efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_mysql_status_mirror_concurrency{node_name=\"$proxysql\"}",
     "legendFormat": "Concurrent Mirror threads"
    },
    {
     "expr": "proxysql_mysql_status_mirror_queue_length{node_name=\"$proxysql\"}",
     "legendFormat": "Mirror queue length (queries)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}",
     "legendFormat": "Query Cache"
    },
    {
     "expr": "proxysql_mysql_status_sqlite3_memory_bytes{node_name=\"$proxysql\"}",
     "legendFormat": "SQLite"
    },
    {
     "expr": "proxysql_mysql_status_connpool_memory_bytes{node_name=\"$proxysql\"}",
     "legendFormat": "Connection Pool"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(proxysql_stats_memory_auth_memory{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_auth_memory{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Used by the Authentication module"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_jemalloc_active{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_active{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Allocated in pages by the Application"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_jemalloc_allocated{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_allocated{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Allocated by the Application"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_jemalloc_mapped{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_mapped{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Extents mapped by the Allocator"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_jemalloc_metadata{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_metadata{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Dedicated to Metadata"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_jemalloc_resident{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_resident{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Physically Resident Data pages Mapped by the Allocator"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_jemalloc_retained{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_retained{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Retained Memory"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_query_digest_memory{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_query_digest_memory{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Memory Used to Store Data"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_sqlite3_memory_bytes{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_sqlite3_memory_bytes{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Used by the Embedded SQLite"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_stack_memory_mysql_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_mysql_threads{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Stack Memory for Mysql Threads"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_stack_memory_admin_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_admin_threads{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Stack Memory for Admin Threads"
    },
    {
     "expr": "max_over_time(proxysql_stats_memory_stack_memory_cluster_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_cluster_threads{node_name=\"$proxysql\"}[5m])",
     "legendFormat": "Stack Memory for Cluster Threads"
    }
   ]
  }
 ]
}