{
 "title": "PXC/Galera Hosts Compare",
 "tags": [
  "Percona",
  "HA_Compare"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mysql_global_status_wsrep_local_state, instance)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mysql_galera_variables_info{instance=~\"$instance\"}, wsrep_cluster_name)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(mysql_galera_variables_info{wsrep_cluster_name =\"$cluster\"}, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service - Ready to Accept Queries",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_ready{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Local State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_local_state{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Desync Mode",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_wsrep_desync{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "repeat": "service",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_cluster_status{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - gcache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "repeat": "service",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_galera_gcache_size_bytes{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - FC (normal traffic)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "repeat": "service",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_flow_control_status{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Ready to Accept Queries",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_ready{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Local State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_local_state{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Desync Mode",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_wsrep_desync{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - Cluster Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_wsrep_cluster_status{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - gcache Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_galera_gcache_size_bytes{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service - FC (normal traffic)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_wsrep_flow_control_status{service_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Galera Cluster Size",
   "type": "graph",
   "description": "Shows the number of members currently connected to the cluster.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max_over_time(mysql_global_status_wsrep_cluster_size[$interval]) or \nmax_over_time(mysql_global_status_wsrep_cluster_size[5m])) * on(service_name) group_left(wsrep_cluster_name) (mysql_galera_variables_info{wsrep_cluster_name=\"$cluster\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Galera Replication Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows figures for the replication latency on group communication. It measures latency from the time point when a message is sent out to the time point when a message is received. As replication is a group operation, this essentially gives you the slowest ACK and longest RTT in the cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "repeat": "service",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Maximum\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Maximum\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Standard Deviation\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Standard Deviation\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Average\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Average\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "min_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Minimum\"}[$interval]) or\nmin_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Minimum\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows figures for the replication latency on group communication. It measures latency from the time point when a message is sent out to the time point when a message is received. As replication is a group operation, this essentially gives you the slowest ACK and longest RTT in the cluster.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Maximum\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Maximum\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Standard Deviation\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Standard Deviation\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "avg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Average\"}[$interval]) or\navg_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Average\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      },
      {
       "expr": "min_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Minimum\"}[$interval]) or\nmin_over_time(mysql_global_status_wsrep_evs_repl_latency{service_name=~\"$service\", aggregator=\"Minimum\"}[5m])",
       "legendFormat": "{{ aggregator }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Replication Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the length of receive and send queues.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_local_recv_queue{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_recv_queue{service_name=~\"$service\"}[5m])",
       "legendFormat": "Receive Queue"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_local_send_queue{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_send_queue{service_name=~\"$service\"}[5m])",
       "legendFormat": "Send Queue"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the length of receive and send queues.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_local_recv_queue{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_recv_queue{service_name=~\"$service\"}[5m])",
       "legendFormat": "Receive Queue"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_local_send_queue{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_local_send_queue{service_name=~\"$service\"}[5m])",
       "legendFormat": "Send Queue"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Flow Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the number of FC_PAUSE events sent/received. They are sent by a node when its replication queue gets too full. If a node is sending out FC messages it indicates a problem.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service\"}[5m])",
       "legendFormat": "FC Messages Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service\"}[5m])",
       "legendFormat": "FC Messages Sent"
      },
      {
       "calculatedInterval": "2m",
       "expr": "(rate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service\"}[5m]))/1000000000",
       "legendFormat": "Paused due to Flow Control"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the number of FC_PAUSE events sent/received. They are sent by a node when its replication queue gets too full. If a node is sending out FC messages it indicates a problem.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_recv{service_name=~\"$service\"}[5m])",
       "legendFormat": "FC Messages Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{service_name=~\"$service\"}[5m])",
       "legendFormat": "FC Messages Sent"
      },
      {
       "calculatedInterval": "2m",
       "expr": "(rate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{service_name=~\"$service\"}[5m]))/1000000000",
       "legendFormat": "Paused due to Flow Control"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Writing Conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the number of local transactions being committed on this node that failed certification (some other node had a commit that conflicted with ours) – client received deadlock error on commit and also the number of local transactions in flight on this node that were aborted because they locked something an applier thread needed – deadlock error anywhere in an open transaction. Spikes in the graph may indicate writing to the same table potentially the same rows from 2 nodes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "repeat": "service",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_local_cert_failures{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_local_cert_failures{service_name=~\"$service\"}[5m])",
       "legendFormat": "Local Cert Failures"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_local_bf_aborts{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_local_bf_aborts{service_name=~\"$service\"}[5m])",
       "legendFormat": "Local Bf Aborts"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the number of local transactions being committed on this node that failed certification (some other node had a commit that conflicted with ours) – client received deadlock error on commit and also the number of local transactions in flight on this node that were aborted because they locked something an applier thread needed – deadlock error anywhere in an open transaction. Spikes in the graph may indicate writing to the same table potentially the same rows from 2 nodes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_local_cert_failures{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_local_cert_failures{service_name=~\"$service\"}[5m])",
       "legendFormat": "Local Cert Failures"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_local_bf_aborts{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_local_bf_aborts{service_name=~\"$service\"}[5m])",
       "legendFormat": "Local Bf Aborts"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Writeset Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the count of transactions received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[5m])",
       "legendFormat": "Transactions Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[5m])",
       "legendFormat": "Transactions Replicated"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the count of transactions received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[5m])",
       "legendFormat": "Transactions Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[5m])",
       "legendFormat": "Transactions Replicated"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Writeset Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "repeat": "service",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[5m])",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[5m])",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Parallelization Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the average distances between highest and lowest seqno that are concurrently applied, committed and can be possibly applied in parallel (potential degree of parallelization).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "repeat": "service",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_apply_window{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_apply_window{service_name=~\"$service\"}[5m])",
       "legendFormat": "Apply Window"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_commit_window{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_commit_window{service_name=~\"$service\"}[5m])",
       "legendFormat": "Commit Window"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_cert_deps_distance{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cert_deps_distance{service_name=~\"$service\"}[5m])",
       "legendFormat": "Cert Deps Distance"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the average distances between highest and lowest seqno that are concurrently applied, committed and can be possibly applied in parallel (potential degree of parallelization).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_apply_window{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_apply_window{service_name=~\"$service\"}[5m])",
       "legendFormat": "Apply Window"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_commit_window{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_commit_window{service_name=~\"$service\"}[5m])",
       "legendFormat": "Commit Window"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_wsrep_cert_deps_distance{service_name=~\"$service\"}[$interval]) or\nmax_over_time(mysql_global_status_wsrep_cert_deps_distance{service_name=~\"$service\"}[5m])",
       "legendFormat": "Cert Deps Distance"
      }
     ]
    }
   ]
  },
  {
   "title": "Available Downtime before SST Required",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows for how long the node can be taken out of the cluster before SST is required. SST is a full state transfer method.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "repeat": "service",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_galera_gcache_size_bytes{service_name=~\"$service\"}/(rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[5m])+rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[5m])) * 300",
       "legendFormat": "Time (5m avg)"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows for how long the node can be taken out of the cluster before SST is required. SST is a full state transfer method.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_galera_gcache_size_bytes{service_name=~\"$service\"}/(rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[5m])+rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[5m])) * 300",
       "legendFormat": "Time (5m avg)"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Writeset Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the average transaction size received/replicated.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "repeat": "service",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[$interval]) / rate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[5m]) / irate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[5m])",
       "legendFormat": "Incoming Transaction Size"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[$interval]) / rate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[5m]) / irate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[5m])",
       "legendFormat": "Replicating Transaction Size"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the average transaction size received/replicated.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[$interval]) / rate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[5m]) / irate(mysql_global_status_wsrep_received{service_name=~\"$service\"}[5m])",
       "legendFormat": "Incoming Transaction Size"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[$interval]) / rate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[$interval]) or irate(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[5m]) / irate(mysql_global_status_wsrep_replicated{service_name=~\"$service\"}[5m])",
       "legendFormat": "Replicating Transaction Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Galera Network Usage Hourly",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "repeat": "service",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[1h])",
       "legendFormat": "Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[1h])",
       "legendFormat": "Replicated"
      }
     ]
    },
    {
     "title": "$service",
     "type": "graph",
     "description": "Shows the bytes of data received from the cluster (any other node) and replicated to the cluster (from this node).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_wsrep_received_bytes{service_name=~\"$service\"}[1h])",
       "legendFormat": "Received"
      },
      {
       "calculatedInterval": "2m",
       "expr": "increase(mysql_global_status_wsrep_replicated_bytes{service_name=~\"$service\"}[1h])",
       "legendFormat": "Replicated"
      }
     ]
    }
   ]
  }
 ]
}